- app/assets/stylesheets/application.scss
- app/views/contents/_app_banner.html.haml
- app/views/contents/_footer.html.haml
- app/views/contents/_header.html.haml
- app/views/contents/index.html.haml
> Create contents index

- app/assets/stylesheets/modules/_contents.scss
- app/controllers/contents_controller.rb
- app/views/contents/_purchase_btn.html.haml
- app/views/contents/index.html.haml
- app/views/contents/show.html.haml
contentsコントローラーで表示するshowアクションのviewを作りました。
商品の詳細情報を確認できるようにするため。
> create contents show

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_new_registrations.scss
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/items/index.html.haml
ユーザー新規登録、ログイン画面のマークアップ実装
必須実装の為
> user_new_login-markup

- Gemfile
- Gemfile.lock
- app/uploaders/image_uploader.rb
- config/initializers/carrierwave.rb
> S3-setting

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_contents_buy.scss
- app/views/contents/_purchase_btn.html.haml
- app/views/contents/buy.html.haml
> buy-page-create

- app/assets/stylesheets/modules/_contents.scss
- app/views/contents/show.html.haml
詳細ページに商品の情報を反映させる
どの商品のかを区別するため
> content-show-severside

- app/assets/stylesheets/modules/_contents_new.scss
- app/views/contents/new.html.haml
> edit content new

- app/controllers/contents_controller.rb
- app/models/content.rb
- app/views/contents/new.html.haml
contentモデルにimagesのバリデーションを追加しました。
> add validation to content.images

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_flash.scss
- app/assets/stylesheets/modules/_new_registrations.scss
- app/models/address.rb
- app/models/user.rb
- app/views/devise/registrations/new_address.html.haml
- app/views/layouts/_notifications.html.haml
- config/application.rb
- config/locales/devise.ja.yml
- config/locales/ja.yml
エラーバリデーションの追加実装
アプリ開発において重要だから
> error_validate

- app/models/content.rb
- app/views/contents/show.html.haml
コンテンツコントローラーを少し編集しました。
カテゴリーidが1000までのアイテムしか出品できない様になっていたため。
> edit contents controller

- app/controllers/contents_controller.rb
- app/views/contents/index.html.haml
商品の中にブランドが記載された商品がなかった際にピックアップブランドが表示されない様にした。
> edit contents controller #2

- app/controllers/contents_controller.rb
> edit contents controller #3

- app/controllers/contents_controller.rb
- app/views/contents/show.html.haml
> change buyer_id to auction_id

- app/assets/stylesheets/modules/_contents_buy.scss
- app/views/contents/buy.html.haml
- app/views/contents/show.html.haml
> buypage_edit

- app/controllers/contents_controller.rb
> contents_controller_buy

- app/controllers/contents_controller.rb
> alert_edit

- app/views/contents/edit.html.haml
商品編集画面のフッターに色を入れた
#why
見やすくするため
> footer_edit

- app/controllers/contents_controller.rb
商品情報編集の編集
画像を全て消した時に追加できなくなっていたため
> edit_sever_side_change

- app/controllers/contents_controller.rb
- app/javascript/category.js
- app/javascript/new.js
> edit_contens

- app/models/user.rb
- app/views/contents/show.html.haml
> change name auction to buy

- app/controllers/contents_controller.rb
auction_idとしていた箇所をbuyer_idに変える作業
> buyer id check

- app/assets/stylesheets/modules/_contents_new.scss
- app/views/contents/edit.html.haml
- app/views/contents/new.html.haml
> returnbtn_edit

- app/assets/stylesheets/modules/_contents.scss
- app/controllers/contents_controller.rb
- app/views/contents/index.html.haml
> add contents list on top page

- config/unicorn.rb
unicorn単体でのデプロイ設定を行いました。
単体テストによりデプロイができているか確認する為。
> Fix_config/unicorn.rb

- config/initializers/carrierwave.rb
aws_access_key_id と aws_secret_access_key の記述変更。
本番環境で unicorn_rails を行いエラーが出力された為。
> Fix_config/initializers/carrierwave.rb

- config/unicorn.rb
unicorn.rb の listen を変更。
nginx と unicorn のソケットを連携させる為。
> Fix_config/unicorn.rb_listen

- config/unicorn.rb
Capistrano 実装による unicorn.rb 内の設定 path 変更。
Capistrano 実装の為。
> Fix_config/unicorn.rb_capistrano

- app/assets/stylesheets/modules/_contents.scss
- app/views/contents/_app_banner.html.haml
- app/views/contents/_footer.html.haml
- app/views/contents/_header.html.haml
- app/views/contents/_purchase_btn.html.haml
- app/views/contents/buy.html.haml
- app/views/contents/edit.html.haml
- app/views/contents/index.html.haml
- app/views/contents/new.html.haml
- app/views/users/show.html.haml
ImageURL の Path を変更。
デプロイ後のImage画像が反映されていなかった為。
> Fix_ImagePath_ForAsset

- app/views/contents/_app_banner.html.haml
- app/views/contents/_footer.html.haml
- app/views/contents/_header.html.haml
- app/views/contents/_purchase_btn.html.haml
- app/views/contents/buy.html.haml
- app/views/contents/edit.html.haml
- app/views/contents/index.html.haml
- app/views/contents/new.html.haml
- app/views/users/show.html.haml
各ファイルの image_tag の参照 Path を変更。
image_tag の参照 Path が間違っていた為。
> Fix_(image_tag)

- app/views/cards/new.html.haml
- app/views/contents/_app_banner.html.haml
- app/views/contents/_footer.html.haml
- app/views/contents/_header.html.haml
- app/views/contents/_purchase_btn.html.haml
- app/views/contents/buy.html.haml
- app/views/contents/edit.html.haml
- app/views/contents/index.html.haml
- app/views/contents/new.html.haml
- app/views/users/show.html.haml
image_tag の Path の頭に / を追加。
デプロイ後の画像反映ができていない為。
> Fix_(image_tag)_Add(/)

- app/assets/stylesheets/modules/_contents.scss
- app/assets/stylesheets/modules/_users_show.scss
image-path を image-url に変更。
デプロイ後、image-path で background-image が反映されなかった為。
> Fix_(image-path → image-url)

- app/controllers/application_controller.rb
- app/controllers/cards_controller.rb
- app/controllers/contents_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/content.rb
> [ WIP ] formatting
